name: FTPS Test

on:
  push:
    branches: [gh-pages]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: ./
        with:
          server: ftp.iconnect-education
          username: teacher.boujaada@gmail.com
          password: ${{ secrets.ftp_password }}
          protocol: ftps
